### ISSUE TITLE
asp.net 2.0 version

### ISSUE THREAD

**Issue by dotnetshadow** [trailmax/AspNetCoreImpersonation#1]
Hi there,

Firstly thanks for providing a great sample

I think there are a couple of changes that need to be made for asp.net 2.0 projects.

Namely the Authentication side of things **IdentityCookieOptions**:  https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x

Also I noticed in your **StopImpersonation** method, you have decorated it with ** [Authorize(Roles = "Admin")]** but this can be problematic, since there could be situation where the user that you are impersonating isn't in the admin role to begin with so you can't stop the impersonation

**Comment by trailmax** [comment]
Yeah, there are a couple of issues that I know of in that implementation and need to update to v2.0.

And good call on the Admin role for de-impersonation - I did not think of it.

I'll get these fixed when I have some spare time.

**Comment by trailmax** [comment]
@dotnetshadow I've updated the blog post and the repo with the version for Core v2. See branch https://github.com/trailmax/AspNetCoreImpersonation/tree/CoreV2

**Comment by dotnetshadow** [comment]
@trailmax thanks you so much I'll give this a try and report back if there are any issues
